source 'https://rubygems.org'

group :development do
  # bundle config local.vagrant ~/.GIT/3rd-party/vagrant
  if ENV['VAGRANT_FROM_GIT']
    # upstream git master currently breaks with libvirt, so use fixes:
    gem 'vagrant', github: 'aspiers/vagrant', branch: 'working'
  else
    gem 'vagrant', '>= 1.6.5', github: 'mitchellh/vagrant', tag: 'v1.6.5'
  end
  gem 'pry'
end

group :plugins do
  gem 'ruby-libvirt', '~> 0.5.2' #, git: 'git://libvirt.org/ruby-libvirt.git', branch: 'master'

  #gem 'vagrant-libvirt', github: 'pradels/vagrant-libvirt', branch: 'master'
  gem 'vagrant-libvirt', github: 'aspiers/vagrant-libvirt', branch: 'working'

  #gem 'fog', github: 'fog/fog', branch: 'master'
  gem 'fog', github: 'aspiers/fog', branch: 'fix/vols'

  gem 'fog-core', github: 'fog/fog-core', branch: 'master'

  gem 'sahara', github: 'jedi4ever/sahara'
end
