#!/bin/bash

set -e

me='vagrant provisioner'

append_to_file () {
    file="$1"
    perl -0777pi -e \
        "s/\n+# Auto-generated by $me.*\n(.*\n)*^# End auto-generated section from $me//m" \
        "$file"

    (
        echo
        echo "# Auto-generated by $me at `date`"
        cat
        echo "# End auto-generated section from $me"
    ) >>"$file"
}

cat <<EOF | append_to_file /etc/fstab
# noauto since the isos are not available until Vagrant sets up the
# synced folder.
/isos/SUSE-CLOUD-SLE11-SP3-DEPS-x86_64-current.iso /srv/tftpboot/suse-11.3/install iso9660 noauto 0 0
/isos/SUSE-CLOUD-4-x86_64-current.iso              /srv/tftpboot/repos/Cloud       iso9660 noauto 0 0
EOF

cat <<EOF | append_to_file /etc/init.d/boot.local
# This has to be done late during boot since the isos are not
# available until Vagrant sets up the synced folder.
mount /srv/tftpboot/repos/Cloud
mount /srv/tftpboot/suse-11.3/install
EOF

mkdir /srv/tftpboot/repos/Cloud

# By the time we get to provisioning, the synced folder is already set up.
mount /srv/tftpboot/suse-11.3/install
mount /srv/tftpboot/repos/Cloud
