#!/bin/bash

set -e

me='vagrant provisioner'
append_to_fstab () {
    perl -0777pi -e \
        "s/\n+# Auto-generated by $me.*\n(.*\n)*^# End auto-generated section from $me//m" \
        /etc/fstab

    (
        echo
        echo "# Auto-generated by $me at `date`"
        # Nicely align columns
        cat | column -t
        echo "# End auto-generated section from $me"
    ) >>/etc/fstab
}

cat <<EOF | append_to_fstab
/isos/SUSE-CLOUD-SLE11-SP3-DEPS-x86_64-current.iso /srv/tftpboot/suse-11.3/install iso9660 defaults 0 0
/isos/SUSE-CLOUD-4-x86_64-current.iso              /srv/tftpboot/repos/Cloud       iso9660 defaults 0 0
EOF

mkdir /srv/tftpboot/repos/Cloud

mount /srv/tftpboot/suse-11.3/install
mount /srv/tftpboot/repos/Cloud
