#!/bin/bash -e
#
# This script is executed at the end of appliance creation.  Here you can do
# one-time actions to modify your appliance before it is ever used, like
# removing files and directories to make it smaller, creating symlinks,
# generating indexes, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance
# (oem = disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
if test -f /studio/profile; then
    . /studio/profile
fi

# read in KIWI utility functions
if test -f /.kconfig; then
    . /.kconfig
fi

echo "Removing EULA on first boot ..."
rm /etc/YaST2/licenses/license.txt

echo "Enabling auto-start of ntp and ssh services on boot ..."
chkconfig ntp on
chkconfig sshd on

echo "Adding vagrant to sudoers"
cat <<EOF >>/etc/sudoers

vagrant ALL=(ALL) NOPASSWD: ALL
EOF
# Ensure vagrant maintains password-less sudo access even after
# Crowbar/Chef hijack /etc/sudoers:
groupadd sysadmin
usermod -G sysadmin vagrant

# This avoids annoyingly long timeouts on reverse DNS
# lookups when connecting via ssh.
echo "Disabling UseDNS in sshd ..."
sed -i 's/^#\?UseDNS.*/UseDNS no/' /etc/ssh/sshd_config

# Default behaviour of less drives me nuts!
sed -i 's/\(LESS="\)/\1-X /' /etc/profile
