#!/bin/sh

cd $(dirname $0)
patch -p1 -d /opt/dell < 0001-Disable-calamari-role-in-Crowbar-for-appliance.patch
patch -p1 -d /opt/dell < 0001-crowbar_register-Add-entry-to-etc-hosts-for-resolvin.patch
