# This builds a vagrant box with a very similar end result to "vagrant
# package", except the .ovf file is taken from this git repository,
# and the .vmdk is taken from the kiwi build.

BOX_NAME = cloud3-admin
VMDK = Crowbar_admin_ReOS_for_OpenStack_summit_2014.x86_64-0.0.1.vmdk

include ../box.make
