# Deprecated! - please consider using OBS instead, as explained in the
# README.md.

# This builds a vagrant box with a very similar end result to "vagrant
# package", except the .ovf file is taken from this git repository,
# and the .vmdk is taken from the kiwi build.

BOX_NAME = cloud7-admin
VMDK = cloud7-admin.x86_64-0.0.1.vmdk

include ../box.make
