# ../Vagrantfile will use this config file to build a cloud with 2 HA
# controllers and 1 compute node.  You'll probably need at least 18GB
# RAM on the host for this!
---
networks:
  management: 192.168.101.0/24  # FIXME: currently only used for libvirt
  crowbar:
    admin_ip: 192.168.124.10
    pool_start: 192.168.124.50  # dummy IP, not actually used
vms:
  - name: DEFAULT
    cpus: 2
    ram: 4000
    box: suse/sles12sp1
  - name: admin
    personality: admin
    primary: true
    box: suse/cloud6-admin
    forward_ports:
      # Set the VAGRANT_INSECURE_PORT_FORWARDS environment variable
      # to 'yes' if you want these forwarded ports accessible from
      # other machines which can route to your host.  This is useful
      # when testing/demoing the cloud from a different machine.
      - {host: 8000, guest: 80}  # Crowbar admin web UI
  - name: controller1
    personality: controller
    ram: 6000
    drbd: true
    sbd: create
    forward_ports:
      # See above note about VAGRANT_INSECURE_PORT_FORWARDS.
      - {host: 7630, guest: 7630}  # Hawk web UI for HA clusters
  - name: controller2
    personality: controller
    ram: 6000
    drbd: true
    sbd: share
    forward_ports:
      # See above note about VAGRANT_INSECURE_PORT_FORWARDS.
      - {host: 7631, guest: 7630}  # Hawk web UI for HA clusters
  - name: compute1
    personality: compute
    ram: 1800
