#!/bin/bash -e
#
# This script is executed at the end of appliance creation.  Here you can do
# one-time actions to modify your appliance before it is ever used, like
# removing files and directories to make it smaller, creating symlinks,
# generating indexes, etc.
#
# The 'kiwi_type' variable will contain the format of the appliance
# (oem = disk image, vmx = VMware, iso = CD/DVD, xen = Xen).
#

# read in some variables
. /studio/profile

# read in KIWI utility functions
. /.kconfig

die () {
    echo >&2 "$*"
    exit 1
}

#==========================================================

if ! long_hostname="`cat /etc/hostname`"; then
    die "Failed to determine hostname"
fi
short_hostname="${long_hostname%%.*}"
if [ "$short_hostname" = "$long_hostname" ]; then
    die "Failed to determine FQDN for hostname ($short_hostname)"
fi
ADMIN_IP=192.168.124.10
if ! grep -q "^$ADMIN_IP " /etc/hosts; then
    echo "$ADMIN_IP   $long_hostname $short_hostname" >> /etc/hosts
fi

systemctl enable crowbar.service

sed -i.orig 's/firstboot.xml/firstboot-suse-openstack-cloud.xml/g' /etc/sysconfig/firstboot

#==========================================================

# This avoids annoyingly long timeouts on reverse DNS
# lookups when connecting via ssh.
echo "Disabling UseDNS in sshd..."
sed -i 's/^#\?UseDNS.*/UseDNS no/' /etc/ssh/sshd_config

# Default behaviour of less drives me nuts!
sed -i 's/\(LESS="\)/\1-X /' /etc/profile

# Reduce grub prompt timeout
echo "Reducing grub timeout..."
sed -i 's/^timeout=[0-9]\+/timeout=2/' /boot/grub2/grub.cfg

cat <<EOF >>/root/.bash_profile
if [ -e /tmp/.crowbar-nodes-roles.cache ]; then
  source /tmp/.crowbar-nodes-roles.cache
fi
EOF

#==========================================================

echo "Setting up zypper repos..."

# -K disables local caching of rpm files, since they are already local
# to the VM (or at least to its host in the NFS / synced folders cases),
# so caching would just unnecessarily bloat the VM.
#
# -G disables GPG check for the repository.
zypper ar -G -K -t yast2  file:///srv/tftpboot/suse-12.1/x86_64/install DEPS-ISO

#==========================================================

echo "Patching Crowbar for appliance..."

# Scrap pointless 45 second tcpdump per interface
sed -i 's/45/1/' /opt/dell/chef/cookbooks/ohai/files/default/plugins/crowbar.rb

# Create the directory for shared glance storage
mkdir -p /var/lib/glance

# Create the NFS export for shared storage for HA PostgreSQL and RabbitMQ
mkdir -p /nfs/{postgresql,rabbitmq}
echo '/nfs <%= @admin_subnet %>/<%= @admin_netmask %>(rw,async,no_root_squash,no_subtree_check)' >> /opt/dell/chef/cookbooks/nfs-server/templates/default/exports.erb

#==========================================================

exit 0