#!/bin/bash

set -e

admin_ip="192.168.124.10"

if [ ! -f ~/.openrc ]; then
    echo "No .openrc file!"
    exit 1
fi

CIRROS_TAR=cirros-0.3.4-x86_64-uec.tar.gz
TEMP=$(mktemp -d)

cleanup() {
    rm -rf $TEMP
}

function findfirst() {
    find $TEMP -name "$1" | head -1
}

trap cleanup INT EXIT

wget -q --no-verbose http://${admin_ip}:8091/files/tempest/$CIRROS_TAR --directory-prefix=$TEMP
tar -xzf $TEMP/$CIRROS_TAR -C $TEMP

source .openrc

echo -n "Adding kernel ... "
KERNEL_ID=$(openstack --insecure image create \
    -f value -c id \
    --public --container-format aki  --disk-format aki \
    --file $(findfirst '*-vmlinuz') \
    "cirros-kernel")
echo "done."

echo -n "Adding ramdisk ... "
RAMDISK_ID=$(openstack --insecure image create \
    -f value -c id \
    --public --container-format ari  --disk-format ari \
    --file $(findfirst '*-initrd') \
    "cirros-ramdisk")
echo "done."

echo -n "Adding image ... "
MACHINE_ID=$(openstack --insecure image create \
    -f value -c id \
    --public --container-format ami --disk-format ami \
    --property kernel_id=$KERNEL_ID \
    --property ramdisk_id=$RAMDISK_ID \
    --file $(findfirst '*.img') \
    "cirros-machine")
echo "done."
